title: new great title
author: AT
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  new great description just for test

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
